name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build release project
      run: flutter build web

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./hosting/web
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v2
        with:
          name: production-files

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hosting/web
